site_name: 'illumos'
repo_name: 'illumos/docs'
repo_url: 'https://github.com/illumos/docs'

pages:
  - 'Home': 'index.md'
  - 'About':
    - 'What is illumos?': 'about/index.md'
    - 'Who uses illumos?': 'about/who.md'
    - 'Features': 'about/features.md'
    - 'Distributions': 'about/distro.md'
    - 'Leadership': 'about/leadership.md'
    - 'FAQ': 'about/faq.md'
    - 'Logo': 'about/logo.md'
  - 'Security': 'security/index.md'
  - 'Flag Days': 'flagdays/index.md'
  - 'History':
    - 'Overview': 'about/history.md'
    - 'Announcement': 'about/announcement.md'
  - 'User Guide':
    - 'Getting Started': 'user-guide/index.md'
    - 'Bug Reporting': 'user-guide/bugs.md'
    - 'Books': 'user-guide/books.md'
    - 'Manual Pages': 'user-guide/manual.md'
    - 'Debugging':
      - 'Overview': 'user-guide/debug.md'
      - 'Systems': 'user-guide/debug-systems.md'
      - 'Applications': 'user-guide/debug-apps.md'
  - 'Development':
    - 'Overview': 'developers/index.md'
    - 'Building illumos': 'developers/build-illumos.md'
    - 'Build times': 'developers/build-times.md'
    - 'Building Components': 'developers/build-components.md'
    - 'Build Datasets': 'developers/build-datasets.md'
    - 'Multiple Workspaces': 'developers/workspaces.md'
    - 'Working Multiple Bugs': 'developers/multibug.md'
    - 'Building with Sun Studio': 'developers/studio.md'
    - 'Comparing with webrev': 'developers/comp-webrev.md'
  - 'Contributing':
    - 'Overview': 'contributing/index.md'
    - 'On Quality': 'contributing/quality.md'
    - 'Quality Death Spiral': 'contributing/qds.md'
    - 'Documentation': 'contributing/docs.md'
  - 'Community':
    - 'Overview': 'community/index.md'
    - 'Mailing Lists': 'community/lists.md'
    - 'Events': 'community/events.md'
    - 'Videos': 'community/videos.md'
    - 'Google Summer of Code':
      - 'Overview': 'community/gsoc.md'
      - 'Student Application': 'community/gsoc-application.md'
      - 'Student Expectations': 'community/gsoc-expectations.md'
      - 'Writing a Proposal': 'community/gsoc-proposal.md'
      - 'Becoming a Mentor': 'community/gsoc-mentor.md'
      - 'Mentoring Application': 'community/gsoc-mentor-application.md'
  - 'Projects': 'projects/index.md'

theme:
  name: null
  custom_dir: 'material-illumos'
  language: en
  logo: 'assets/images/illumos.svg'
  palette:
  feature:
    tabs: false
  include_search_page: false
  search_index_only: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/illumos'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
